import type { Metadata } from "next";
import { Work_Sans , Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/Sections/Navbar/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/Sections/Footer/Footer";

const workSans = Work_Sans({
  weight: ['100', '200', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: "--font-worksans"
})

const jakarta = Plus_Jakarta_Sans({
  weight: ['400' , '500' ,'600' ,'700' ,'800'],
  subsets: ['latin'],
  variable: "--font-jakarta",
})

export const metadata: Metadata = {
  title: "MetaBolg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${workSans.variable} ${jakarta.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
