export const blogs = [
    {
      id: 1,
      title: "The Future of Web Development in 2025",
      authername: "Elizabeth_Slavin",
      cover: "/Cover/1.png",
      autherimage: "/Authers/Elizabeth_Slavin.png",
      date: "2025-01-05",
      catogray: "Technology",
    },
    {
      id: 2,
      title: "Why Simplicity Wins in UI Design",
      authername: "Eric_Smith",
      cover: "/Cover/2.png",
      autherimage: "/Authers/Eric_Smith.png",
      date: "2025-01-10",
      catogray: "Design",
    },
    {
      id: 3,
      title: "Building Scalable Blogs with Modern Stacks",
      authername: "Ernie_Smith",
      cover: "/Cover/3.png",
      autherimage: "/Authers/Ernie_Smith.png",
      date: "2025-01-15",
      catogray: "Development",
    },
    {
      id: 4,
      title: "Content Strategy That Actually Converts",
      authername: "Jason_Francisco",
      cover: "/Cover/4.png",
      autherimage: "/Authers/Jason_Francisco.png",
      date: "2025-01-18",
      catogray: "Marketing",
    },
    {
      id: 5,
      title: "How AI Is Changing Blogging Forever",
      authername: "Tracey_Wilson",
      cover: "/Cover/5.png",
      autherimage: "/Authers/Tracey_Wilson.png",
      date: "2025-01-22",
      catogray: "AI",
    },
    {
      id: 6,
      title: "SEO Basics Every Blogger Must Know",
      authername: "Elizabeth_Slavin",
      cover: "/Cover/6.png",
      autherimage: "/Authers/Elizabeth_Slavin.png",
      date: "2025-01-25",
      catogray: "SEO",
    },
    {
      id: 7,
      title: "Writing Clean and Maintainable Code",
      authername: "Eric_Smith",
      cover: "/Cover/7.png",
      autherimage: "/Authers/Eric_Smith.png",
      date: "2025-01-28",
      catogray: "Programming",
    },
    {
      id: 8,
      title: "From Idea to Published Article",
      authername: "Ernie_Smith",
      cover: "/Cover/8.png",
      autherimage: "/Authers/Ernie_Smith.png",
      date: "2025-02-01",
      catogray: "Writing",
    },
    {
      id: 9,
      title: "Design Systems for Large Blog Platforms",
      authername: "Tracey_Wilson",
      cover: "/Cover/9.png",
      autherimage: "/Authers/Tracey_Wilson.png",
      date: "2025-02-05",
      catogray: "UI/UX",
    },
  ]
  